### ISSUE TITLE
[MOVED] Add mobility data for Colombia

### ISSUE THREAD

**Issue by thoat** [unicef/magicbox-open-api#54]
# Background
The mobility data we currently have in place for Columbia is by specific dates in a year (e.g. 2015/02/03). Recently, we are given mobility data by day-of-week (e.g. Monday) and are informed that will be the direction moving forward.  We need to add this new dataset to our API and adjust the front-end apps (e.g. [unicef/magicbox-maps](https://github.com/unicef/magicbox-maps) and [unicef/magicbox-maps-prototype](https://github.com/unicef/magicbox-maps-prototype) to correctly fetch and visualize the data.

# Task breakdown
- [ ] Add the new dataset to [magicbox-open-api/public/aggregations/mobility](https://github.com/unicef/magicbox-open-api/tree/master/public/aggregations/mobility) (and maybe the private server as well?). This could be as straightforward as placing a the `.csv.` files, which we readily have, into the said folder. 
- [ ] Adjust the code logic in the front-end app(s) to fetch and visualize this data. This can be broken down to sub-tasks, such as:
   - [x] First, add activity data as the default mobility to be visualized as soon as the app is loaded. This task is hosted at unicef/magicbox-maps-prototype#8
   - [ ] Add _actual_ mobility data. This task is hosted at ... //TODO: add Vinit's PR here.

**Comment by thoat** [comment]
This issue has been moved to unicef/magicbox-maps-prototype#13
